name: passgrinder
description: PassGrinder is a free password generator that takes your one master password and delivers a twenty-character strong password based on the website URL, domain name, app name, or unique phrase you choose.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  crypto: ^3.0.3
  file: ^7.0.0
  font_awesome_flutter: ^10.7.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  yaml: ^3.1.0

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  macos:
    enable: true
    generate: true
  windows:
    enable: true
    generate: true
  linux:
    enable: true
    generate: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/app_icon.png
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
